version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'users_postgres_db'
    environment:
      - 'POSTGRES_DB=users'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=0000'
    ports:
      - "5432:5432"